---
title: "Generating Oscillatory Dynamics and Fixing Noise Dynamics"
author: "Kaitlyn Stocker"
date: "2/12/2017"
output: html_document
---
```{r, include=FALSE}
library(rstan)
```

```{r, include=FALSE}
#Initial Conditions
n.now <- 763000
s.now <- .108*n.now
i.now <- n.now/1960
r.now <- n.now - i.now - s.now 
b.now <- 0 

#Stan Code
Stan_sim_26betas <- as.character("
                            data {
	int<lower=1> N; // time steps
  real P[N]; //population size
	int <lower=0> I[N];
	int <lower=0> S[N];
}


parameters {
	real<lower=0, upper=20> beta[26];
}

transformed parameters {
  real<lower=0, upper=20> betaseq[26*20];
  for(n in 1:26){
  for(m in 0:19){
betaseq[n + 26*m] = beta[n];
  }
}
}

model {
	//priors
	beta[26] ~ gamma(20, 2);

	//likelihood
	for (n in 2:N){
		I[n] ~ neg_binomial_2(betaseq[n-1]*I[n-1]*S[n-1]/P[n-1], I[n-1]);
	}
}     ")

Stan_reconstructed_26betas <- as.character("
data {
	int<lower=1> N; // time steps
  real P[N]; //population size
	int <lower=0> I[N]; // infecteds 
	int  Z[N]; // Zt 
}

parameters {
  real <lower=P[1]/100, upper= P[N]> Sbar;
	real<lower=0, upper=20> beta[26];
}

transformed parameters {
  real<lower=0, upper=20> betaseq[26*20];
  for(n in 1:26){
  for(m in 0:20){
betaseq[n + 26*m] = beta[n];
  }
}
}

model {
	//priors
  Sbar ~ normal(P[1]/2, P[1]/10);
	beta[26] ~ gamma(20,2);

	//likelihood
	for (n in 2:N){
		I[n] ~ neg_binomial_2(betaseq[n-1]*I[n-1]*(Z[n-1]+Sbar)/P[n-1], I[n-1]);
	}
}    ")


```

Generating Oscillatory Dynamics
```{r, echo=FALSE}
Sim <- function(beta, n.now, i.now, s.now, r.now, b.now) {

results <- as.data.frame(matrix(c(i.now, s.now, r.now, b.now, n.now), nrow=1))
names(results) <- c("I", "S", "R", "B", "N")
   for(i in 1:500){
    if(s.now*i.now >0){
    i.next <- rnbinom(n=1, mu=beta*i.now*s.now/n.now, size=i.now) 
    b.now <- birthrate*n.now
    s.now <- s.now - i.next + b.now
    r.now <- r.now + i.now
    n.now <- n.now + b.now
    i.now <- i.next
    results <- rbind(results, c(i.now, s.now, r.now, b.now, n.now))
    }
    else {break}
  }
return(results)
}

#Initial Conditions 
n.now <- 763000
s.now <- .108*n.now
i.now <- n.now/3000 #n.now/3920
r.now <- n.now - i.now - s.now 
beta <- 8 #520/56
birthrate <- 1/(70*26)
b.now <- 0


#Run Simulation
simdata <- Sim(beta=beta, n.now=n.now, i.now=i.now, s.now=s.now, r.now=r.now, b.now=b.now)

#Define Time Steps
T<- cumsum(rexp(length(simdata$I), rate=(1)))
I <- simdata$I
S_sim <- simdata$S
n <- simdata$N
R <- simdata$R


#Plot Simulation
ggplot(simdata, aes(x=T)) +
  geom_line(aes(y=S, col="S"))+
  geom_line(aes(y=I, col="I"))+
  geom_line(aes(y=R, col="R"))+
  labs(x="Time Steps", y = "Number of Individuals", title = "Simulated Epidemic Dynamics")

ggplot(simdata, aes(x=T)) +
  geom_line(aes(y=I)) +
  labs(x="Biweek", y="Number of Infecteds", title="Infected Dynamics")
```
```{r, echo=FALSE}
#Reconstructing Z dynamics 
cumbirths <- cumsum(simdata$B)
cuminfecteds <- cumsum(simdata$I)
cumulativeinfo <- as.data.frame(matrix(c(cumbirths, cuminfecteds), nrow=length(cuminfecteds)))
names(cumulativeinfo) <- c("cumbirths", "cuminfecteds")


#plot(cumbirths ~ cuminfecteds)

regression <- lm(cumbirths ~ 1, offset=(cuminfecteds))
#summary(regression)

Z <- as.vector(resid(regression))
#summary(Z)

ggplot(simdata, aes(x=T))+
  geom_line(aes(y=S, col="S"))+
  geom_line(aes(y=Z, col="Z"))+
  labs(x="Time", y="Number of Susceptibles", title="Reconstructed Dynamics")
```
```{r, include=FALSE}
#Preparing Data for Bayes
I<- simdata$I
n <- simdata$N

time_added<-0
for(i in 2:(length(T))){
  time_added[i] <- T[i] - T[i-1]
}

data_z <- list(N=length(I), P=as.integer(n), I=as.integer(I), Z=as.integer(Z), time_added=time_added)

```
```{r, include=FALSE}
# Stan_z <- as.character("
# data {
# 	int<lower=1> N; // time steps
#   real P[N]; //population size
#   real time_added[N];
# 	int <lower=0> I[N]; // infecteds 
# 	int  Z[N]; // Zt 
# }
# 
# parameters {
#   real <lower=P[1]/100, upper= P[N]> Sbar;
# 	real<lower=0, upper=50> beta;
#   real<lower=0, upper=5> gamma;
# }
# 
# model {
# 	//priors
#   Sbar ~ normal(P[1]/2, P[1]/10);
# 	beta ~ gamma(20, 2);
#   gamma ~ gamma(2,1);
# 
# 	//likelihood
# 	for (n in 2:N){
# 		I[n] ~ neg_binomial_2(beta*I[n-1]*(Z[n-1]+Sbar)/P[n-1], I[n-1]);
#     time_added[n]~exponential_log(gamma);
#   }
# }
# 
#                             ")
# 
# bayes_reconstructed <- stan(model_code = Stan_z, data=data_z, iter=500000, chains=4)
```
```{r, echo=FALSE}
# Sbar <- extract(bayes_reconstructed, 'Sbar')
# Sbar <- unlist(Sbar, use.names=FALSE)
# lowlim_Sbar <- quantile(Sbar, probs=.025, names=FALSE)
# uplim_Sbar <- quantile(Sbar, probs=.975, names=FALSE)
# 
# S_lower <- lowlim_Sbar + Z
# S_upper <- uplim_Sbar + Z
# 
# ggplot(simdata, aes(x=T))+
#   geom_line(aes(y=S, col="S"))+
#   geom_line(aes(y=S_lower, col="S_lower"))+
#   geom_line(aes(y=S_upper, col="S_upper"))+
#   labs(x="time", y="Number of Susceptibles", title="Reconstructed vs. Simulated Susceptible Dynamics")
```
```{r, include=FALSE}
# ##Running Bayes with True Susceptible Dynamics 
# S_sim <- simdata$S
# R<- simdata$R
# 
# data_sim <- list(N=length(I), P=as.integer(n), I=as.integer(I), S=as.integer(S_sim), time_added=time_added)
# 
# SIRstancode <- as.character("
#                             data {
# 	int<lower=1> N; // time steps
#   real P[N]; //population size
#   real time_added[N];
# 	int <lower=0> I[N];
# 	int <lower=0> S[N];
# }
# 
# 
# parameters {
# 	real<lower=0, upper=50> beta;
#   real<lower=0, upper=5> gamma;
# 
# }
# 
# model {
# 	//priors
# 	beta ~ gamma(5, 2);
#   gamma ~ gamma(2,1);
# 	//likelihood
# 	for (n in 2:N){
# 		I[n] ~ neg_binomial_2(beta*I[n-1]*S[n-1]/P[n-1], I[n-1]);
#     time_added[n]~exponential_log(gamma);
#   }
# }
# 
#                             ")
# 
# bayes_sim <- stan(model_code = SIRstancode, data=data_sim, iter=500000, chains=4)
```
```{r, echo=FALSE}
# bayes_reconstructed
```


Generating Oscillatory Dynamics: Seasonal Betas
```{r, echo=FALSE}
t<-seq(0,26,1)
beta_26 <- 0
for(i in 1:26){
  beta_26[i] <- 9.29*(1+.01*cos((pi/26)*t[i]))
}
rm(t)
beta_26 <- rep(beta_26, 20)

Sim <- function(beta, n.now, i.now, s.now, r.now, b.now) {

results <- as.data.frame(matrix(c(i.now, s.now, r.now, b.now, n.now), nrow=1))
names(results) <- c("I", "S", "R", "B", "N")
   for(i in 1:500){
    if(s.now*i.now >0){
    i.next <- rnbinom(n=1, mu=beta[i]*i.now*s.now/n.now, size=i.now) 
    b.now <- rgamma(1, shape=2, scale=.00013699)*n.now
    s.now <- s.now - i.next + b.now
    r.now <- r.now + i.now
    n.now <- n.now + b.now
    i.now <- i.next
    results <- rbind(results, c(i.now, s.now, r.now, b.now, n.now))
    }
    else {break}
  }
return(results)
}

  
simdata <- Sim(beta=beta_26, n.now=n.now, i.now=i.now, s.now=s.now, r.now=r.now, b.now=b.now)

#Pull out Simulation Data and Create Time Vector 
I <- simdata$I
B <- simdata$B
S_sim <- simdata$S
n <- simdata$N
T<- cumsum(rexp(length(I), rate=(1/2))) #infectious period=13 days
time_added<-0
for(i in 2:(length(T))){
  time_added[i] <- T[i] - T[i-1]
}

#Plot Simulation
ggplot(simdata, aes(x=T)) +
  geom_line(aes(y=S, col="S"))+
  geom_line(aes(y=I, col="I"))+
  geom_line(aes(y=R, col="R"))+
  labs(x="Time Steps", y = "Number of Individuals", title = "Simulated Dynamics, Seasonally Changing Betas")

ggplot(simdata, aes(x=T)) +
  geom_line(aes(y=I)) +
  labs(x="Biweek", y="Number of Infecteds", title="Infected Dynamics")

#Reconstructing Z dynamics 
cumbirths <- cumsum(B)
cuminfecteds <- cumsum(I)
cumulativeinfo <- as.data.frame(matrix(c(cumbirths, cuminfecteds), nrow=length(cuminfecteds)))
names(cumulativeinfo) <- c("cumbirths", "cuminfecteds")

regression <- lm(cumbirths ~ 1, offset=(cuminfecteds))

Z <- as.vector(resid(regression))

ggplot(simdata, aes(x=T))+
  geom_line(aes(y=S, col="S"))+
  geom_line(aes(y=Z, col="Z"))+
  labs(x="Time", y="Number of Susceptibles", title="Reconstructed Dynamics")

```
```{r, include=FALSE}
# #Run Bayes
# data_reconstructed <- list(N=length(I), P=as.integer(n), I=as.integer(I), Z=as.integer(Z))
# 
# bayes_reconstructed <- stan(model_code = Stan_reconstructed_26betas, data=data_reconstructed, iter=500000, chains=4, pars=c("beta", "Sbar"), include=TRUE)

#Run Bayes for Simulation
# data_sim <- list(N=length(I), P=as.integer(n), I=as.integer(I), S=as.integer(S_sim))
# 
# bayes_sim <- stan(model_code = Stan_sim_26betas, data=data_sim, iter=500000, chains=4, pars=c("beta"), include=TRUE)
```
```{r, echo=FALSE}
# #Plot S_reconstructed
# Sbar <- extract(bayes_reconstructed, 'Sbar')
# Sbar <- unlist(Sbar, use.names=FALSE)
# lowlim_Sbar <- quantile(Sbar, probs=.025, names=FALSE)
# uplim_Sbar <- quantile(Sbar, probs=.975, names=FALSE)
# 
# S_lower <- lowlim_Sbar + Z
# S_upper <- uplim_Sbar + Z
# 
# ggplot(simdata, aes(x=T))+
#   geom_line(aes(y=S, col="S"))+
#   geom_line(aes(y=S_lower, col="S_lower"))+
#   geom_line(aes(y=S_upper, col="S_upper"))+
#   labs(x="time", y="Number of Susceptibles", title="Reconstructed vs. Simulated Susceptible Dynamics")
```
```{r, echo=FALSE}
#Checking if 95% Credible Intervals Contain True Betas for the Simulated Results
# bayes_sim_extracted <- extract(bayes_sim, permuted=TRUE)
# beta_<-bayes_sim_extracted$beta
# 
# beta<- matrix(nrow=1000000, ncol=28)
# for(i in 1:26){
#   beta[,i] <- beta_[,i]
# }
# 
# lowlimbeta_sim <- c()
# uplimbeta_sim <- c()
# containbeta_sim <- c()
# 
# for(i in 1:26){lowlimbeta_sim[i] <- quantile(beta[,i], probs=.025, names=FALSE)
#               uplimbeta_sim[i] <- quantile(beta[,i], probs=.975, names =FALSE)
#               containbeta_sim[i]<- ifelse(lowlimbeta_sim[i] <= beta_26[i] & uplimbeta_sim[i] >= beta_26[i], 1, 0)
# }


# #Checking if 95% Credible Intervals Contain True Betas for the Reconstructed Results 
# bayes_sr_extracted <- extract(bayes_reconstructed, permuted=TRUE)
# beta_<-bayes_sr_extracted$beta
# sbar <- extract(bayes_reconstructed, 'Sbar', permuted=TRUE)
# sbar <- unlist(sbar, use.names=FALSE)
# 
# beta<- matrix(nrow=1000000, ncol=28)
# for(i in 1:26){
#   beta[,i] <- beta_[,i]
# }
# 
# lowlimbeta_sr <- c()
# uplimbeta_sr <- c()
# containbeta_sr <- c()
# for(i in 1:26){lowlimbeta_sr[i] <- quantile(beta[,i], probs=.025, names=FALSE)
#               uplimbeta_sr[i] <- quantile(beta[,i], probs=.975, names =FALSE)
#               containbeta_sr[i]<- ifelse(lowlimbeta_sr[i]<=beta_26[i] & uplimbeta_sr[i]>=beta_26[i],1,0)
# }
# 
# 
# lowlimsbar <- quantile(sbar, probs=.025, names=FALSE)
# uplimsbar <- quantile(sbar, probs=.975, names =FALSE)
# containssbar<- ifelse(lowlimsbar <= mean(S_sim) & uplimsbar >= mean(S_sim), 1, 0)

```
```{r, echo=FALSE}
# bayes_reconstructed
# 
# containbeta_sr
# containssbar
```

