---
title: 'Multi-City Measles Data'
author: "Kaitlyn Stocker"
date: "3/30/2017"
output: html_document
---

```{r Libraries, include=FALSE}
library(dplyr)
library(rstan)
library(locfit)
```

```{r Functions, include=FALSE}
Sim <- function(beta, city, s_prop, i_prop, plot) {
  i.now <- i_prop*city$pop[1]
  s.now <- s_prop*city$pop[1]
  r.now <- city$pop[1]-i.now-s.now
  cases <- city$cases[1]

  results <- as.data.frame(matrix(c(i.now, s.now, r.now, cases), nrow=1))
  names(results) <- c("I", "S", "R", "Cases")
    for(i in 1:545){
     if(s.now*i.now >0){
      n.now <- city$pop[i]
      i.next <- beta[i]*(i.now^.975)*s.now/n.now
      b.now <- city$rec[i]
      s.now <- s.now - i.next + b.now
      r.now <- r.now + i.now
      i.now <- i.next
      cases <- i.now/city$rho[i]
  results <- rbind(results, c(i.now, s.now, r.now, cases))
    }
    else {break}
    }
  
    sim_plot <- ggplot(city, aes(x=number))+
               geom_line(aes(y=cases, col="Incidence Data"))+
               geom_line(aes(y=results$Cases, col="Simulated Cases"))+
               labs(x="Biweek", y="Number of Cases")
    if(plot==TRUE){return(list(results, sim_plot))}
    
    if(plot==FALSE){return(results)}

}

read_in_city <- function(city_, naremove){

  df <- measles %>%
  filter(year>1919 & year <1941) %>%
  filter(loc == city_) %>%
  select(biweek, year, cases, pop, rec) %>%
  mutate(number = seq(1, 546, 1))
  
  if(naremove==TRUE){
  for(i in 1:nrow(df)){
    if(is.na(df$cases[i])==TRUE){
      df$cases[i] <- (df$cases[i-1]+df$cases[i+2])/2
    }
  }
  }
  
  for(i in 1:nrow(df)){
    if(is.na(df$cases[i])==FALSE & df$cases[i]==0){
      df$cases[i]<-0.5
    }
  }
  
  betas <- measles_betas %>%
  filter(city == city_) %>%
  select(contains("biweek"))
  
  betas <- unname(unlist(betas[1,]))
  
  return(list(df=df, betas=betas))
} #pass city as character

gaussian_kernel <- function(x) {
  (1/sqrt(2*pi))*exp(-x^2/2)
}

gaussian_sum <- function(i, m) {
  gaussian_sum <- 0
  for(k in 1:m){
      gaussian_sum <- sum(gaussian_kernel((x.n[i,k]-x0[i])/which.diff[i]))
      return(gaussian_sum)
    }
}

gaussian_regression <- function(city, scale){
  cumbirths <- cumsum(city$rec)
  cumcases <- as.numeric(cumsum(city$cases))
  
  ord <- order(cumcases)
  c.cases <- cumcases[ord] 
  c.births <- cumbirths[ord] 

  m <- floor(length(cumcases)*(scale)) #SCALE GOES HERE
  h <- m/2

  x0<-0
  diffs<-matrix(nrow=length(cumcases), ncol=length(cumcases))
  which.diff<-0
  x.n <- matrix(nrow=length(cumcases), ncol=m)
  y.n <- matrix(nrow=length(cumcases), ncol=m)

  for(i in 1:length(cumcases)){
  x0[i] <- c.cases[i] #set focal x 
  diffs[i,] <- abs(c.cases - x0[i]) #difference between each datapoint and x0 (x value difference)
  which.diff[i] <- sort(diffs[i,])[m] #This returns the mth smallest difference between c.births (did I mean c.cases? I must have.) and x0. 

  if(length(c.cases[diffs[i,] <= which.diff[i]])<m){
    x.n[i,] <- c(c.cases[diffs[i,] <= which.diff[i]], rep(0, length.out=(m-length(c.cases[diffs[i,] <= which.diff[i]])))) #select m closest x values to focal x
  y.n[i,] <- c(c.births[diffs[i,] <= which.diff[i]], 0) #select m closest corresponding y valeus 
  }
  else{
  x.n[i,] <- head(c.cases[diffs[i,] <= which.diff[i]], m) #select m closest x values to focal x
  y.n[i,] <- head(c.births[diffs[i,] <= which.diff[i]], m) #select m closest corresponding y valeus 
  }
  }
  

gaussian_kernel <- function(x) {
  (1/sqrt(2*pi))*exp(-x^2/2)
}

gaussian_sum <- function(i, m) {
  gaussian_sum <- 0
  for(k in 1:m){
      gaussian_sum <- sum(gaussian_kernel((x.n[i,k]-x0[i])/which.diff[i]))
      return(gaussian_sum)
    }
}
  
  x.wt.gaus <- matrix(nrow=length(cumcases), ncol=m)
  x.coeffs.gaus <- 0
  for(i in 1:length(cumcases)){
    for(k in 1:m){
  x.wt.gaus[i,k]<- gaussian_kernel(x=(x.n[i,k] - x0[i])/which.diff[i])/gaussian_sum(i,m)
  }
  }
  
  reg.gaus <- lapply(1:length(cumcases), function(x) lm(y.n[x,]~x.n[x,], weights = x.wt.gaus[x,]))

  x.coeffs.gaus <-0
  x.intercept.gaus <-0
  y.fit.gaus <- 0
  for(i in 1:length(reg.gaus)){
    x.coeffs.gaus[i] <- as.numeric(coef(reg.gaus[[i]])[2])
    x.intercept.gaus[i] <- as.numeric(coef(reg.gaus[[i]])[1])
    y.fit.gaus[i] <- x.coeffs.gaus[i]*c.cases[i]+x.intercept.gaus[i]
  }

T <- seq(1, 546, 1)  
x.coeffs.gaus.smooth <- fitted(loess(x.coeffs.gaus ~ T))
y.fit.gaus.smooth <-0
for(i in 1:length(x.coeffs.gaus.smooth)){
  y.fit.gaus.smooth[i] <- x.coeffs.gaus.smooth[i]*c.cases[i] + x.intercept.gaus[i]
}

return(list(y.fit.gaus=y.fit.gaus, y.fit.gaus.smooth=y.fit.gaus.smooth, x.coeffs.gaus=x.coeffs.gaus, x.coeffs.gaus.smooth=x.coeffs.gaus.smooth))
}

y_hat_linear <- function(x,y){
  as.numeric(fitted(lm(y~x)))
}

SSE <- function(y_hat, y){
  SSE<-0
  for(i in seq_along(y)){
  SSE <- sum((y[i]- y_hat[i])^2)
  return(SSE)
  }
}

linear_reconstruction <- function(city){
  cumbirths <- cumsum(city$rec)
  cumcases <- as.numeric(cumsum(city$cases))

  regression_linear <- lm(cumbirths ~ cumcases) 
  Z_linear <- as.vector(resid(regression_linear))
  
  return(list(cumbirths, cumcases, Z_linear))
}

local_regression <- function(city, scale){
  cumbirths <- cumsum(city$rec)
  cumcases <- as.numeric(cumsum(city$cases))
  
  gaus_regression_S <- gaussian_regression(city=city, scale=scale)
  gaus_regression_I <- gaussian_regression(city=city, scale=scale)

  city$Z_gaus <- cumbirths - gaus_regression_S$y.fit.gaus
  city$I_gaus <- city$cases*gaus_regression_I$x.coeffs.gaus
  
  city$Z_linear <- linear_reconstruction(city)[[3]]
  city$rho <- gaus_regression_I$x.coeffs.gaus
  
  return(city)
}

SR_plot <- function(city, name){
    ggplot(city, aes(x=number))+
              geom_line(aes(y=Z_gaus, col="Local Regression Estimate of Z")) +
              geom_line(aes(y=Z_linear, col="Linear Regression Estimate of Z"))+
              labs(x="Biweek", y="Z", title= name)

}

IR_plot <- function(city, name){
  ggplot(city, aes(x=number)) +
              geom_line(aes(y=cases, col="Reported Cases")) +
              geom_line(aes(y=I_gaus, col="Estimate of True Infecteds"))+
              labs(x="Biweek", y="Infecteds/Cases", title = name)
}

rho_plot <- function(city, name){
  ggplot(city, aes(x=number)) +
                geom_line(aes(y=rho, col="rho"))+
                labs(x="biweek", y="estimated rho", title = name)
}

optim_bandwidth <- function(city){
  cumbirths <- cumsum(city$rec)
  cumcases <- as.numeric(cumsum(city$cases))
  
  h<- seq(0.05, 0.89, 0.01)
  SSE1_gaus <- c()
  for(i in seq_along(h)){
    if(SSE(y=cumbirths, y_hat=gaussian_regression(city=city, scale=h[i])[[1]]))
    SSE1_gaus[i] <- SSE(y=cumbirths, y_hat=gaussian_regression(city=city, scale=h[i])[[1]])
  }

  SSE2_gaus <- c()
  for(i in seq_along(h)){
    SSE2_gaus[i] <- SSE(y=y_hat_linear(x=cumcases, y=cumbirths), 
                        y_hat=gaussian_regression(city=city, scale=h[i])[[1]])
  }

  SSE_optim_gaus <- which.min(abs(SSE1_gaus-SSE2_gaus)) #Find where SSE1 and SSE2 intersect

  #Select Optimum scale value
  scale_optim_gaus <- h[SSE_optim_gaus]

  return(scale_optim_gaus)
}

bayes_data <- function(city){
  return(list(N=length(city$number), P=as.integer(city$pop), I=as.integer(city$I_gaus),
              Z=as.integer(city$Z_gaus), Zmin=as.integer(abs(min(city$Z_gaus)))))
}

run_bayes <- function(city, which_stan){
  data <- list(N=length(city$number), P=as.integer(city$pop), I=as.integer(city$I_gaus),
              Z=as.integer(city$Z_gaus), Zmin=as.integer(abs(min(city$Z_gaus))))
  
Stan_z_mod <- as.character("
data {
	int<lower=1> N; // time steps
  real P[N]; //population size
	int <lower=0> I[N]; // infecteds
	int  Z[N]; // Zt
  int <lower=0> Zmin;
}

parameters {
  real <lower=Zmin, upper= P[N]> Sbar;
	real<lower=5, upper=100> beta[26];
}

model {
	//priors
  Sbar ~ normal(Zmin, P[1]/10);
	beta[26] ~ gamma(7,5);

	//likelihood
	for (n in 2:N){
  I[n] ~ neg_binomial_2(beta[n%26+1]*(I[n-1]^.975)*(Z[n-1]+Sbar)/P[n-1], I[n-1]);
  }
}    ") 


Stan_z_mod_low_pop <- as.character("
data {
	int<lower=1> N; // time steps
  real P[N]; //population size
	int <lower=0> I[N]; // infecteds
	int  Z[N]; // Zt
  int <lower=0> Zmin;
}

parameters {
  real <lower=Zmin, upper= P[N]> Sbar;
	real<lower=0, upper=200> beta[26];
}

model {
	//priors
  Sbar ~ normal(P[1]/10, P[1]/10);
	beta[26] ~ gamma(10,4);

	//likelihood
	for (n in 2:N){
  I[n] ~ neg_binomial_2(beta[n%26+1]*(I[n-1]^.975)*(Z[n-1]+Sbar)/P[n-1], I[n-1]);
  }
}    ") 

if(which_stan == "low_pop"){
bayes_z <- stan(model_code = Stan_z_mod_low_pop, data=data, iter=500000, chains=4, pars=c("beta", "Sbar"), include=TRUE)
}

if(which_stan == "high_pop"){
  bayes_z <- stan(model_code = Stan_z_mod, data=data, iter=500000, chains=4, pars=c("beta", "Sbar"), include=TRUE)
}

else{bayes_z <- "error: which_stan"}
return(bayes_z)
}

accuracy_check <- function(betas, bayes){
  betas_bayes <- extract(bayes, permuted=TRUE)
  beta_ <- betas_bayes$beta
  Sbar <- betas_bayes$Sbar
  
  beta<- matrix(nrow=1000000, ncol=26)
  for(i in 2:27){
    beta[,i-1] <- beta_[,i%%26+1]
  }
  
  lowlimbeta_sr <- c()
  uplimbeta_sr <- c()
  containbeta_sr <- c()
  for(i in 1:26){lowlimbeta_sr[i] <- quantile(beta[,i], probs=.025, names=FALSE)
                uplimbeta_sr[i] <- quantile(beta[,i], probs=.975, names =FALSE)
                containbeta_sr[i]<- ifelse(lowlimbeta_sr[i] <= betas[i] & uplimbeta_sr[i] 
                                           >=betas[i], 1, 0)
  }


  beta_estimate <- c()
  for(i in 1:26){
    beta_estimate[i] <- quantile(beta[,i], probs=.5, names = FALSE)
  }

  
  lowlim_Sbar <- quantile(Sbar, probs=.025, names=FALSE)
  median_Sbar <- quantile(Sbar, probs=.5, names=FALSE)
  uplim_Sbar <- quantile(Sbar, probs=.975, names=FALSE)
  
  #take difference of paper values and my estimates
  beta_resid <- beta_estimate - betas
  beta_percent_error <- beta_resid/betas

return(list(containbeta_sr=containbeta_sr, beta_resid=summary(beta_resid), beta_percent_error=summary(beta_percent_error), beta_estimate = beta_estimate, sbar_estimate=c(sbar_lower = lowlim_Sbar, sbar_median=median_Sbar, sbar_upper = uplim_Sbar)))
}

fix_na <- function(df, m, k, j){
  for(i in 1:length(m)){
  df$cases[m[i]] <- (df$cases[k] + df$cases[j])/2
  }
  return(df)
}

choose_s_init <- function(city, betas, bayes){
  beta_est <- accuracy_check(betas, bayes)$beta_estimate
  
  s_prop <- seq(0.025, 0.05, 0.0001)#check with this interval, then bump it to 0.00001
  
  x<-seq(1, length(s_prop), 1)
  
 mean_square_error <- sapply(x, function(x){
  sim <- Sim(beta=rep_len(beta_est, length.out = 546), city=city, s_prop[x], 
             plot=FALSE)
  mean_square_error <- sum((sim$Cases/city$pop-city$cases/city$pop)^2)
  return(mean_square_error)
}
)
 return(list(mse=mean_square_error, s_prop=s_prop))
}

choose_initials <- function(city, betas, bayes){
  beta_est <- accuracy_check(betas, bayes)$beta_estimate
  
  s_prop <- seq(0.025, 0.05, 0.00025)#check with this interval, then bump it to   
                                    #0.00001 
  
  i_prop <- seq(0, 0.001, length.out=length(s_prop))
  
  x<-seq(1, length(s_prop), 1)
  
  mse <- function(x,y){
    sim <- Sim(beta=rep_len(beta_est, length.out = 546), city=city, 
               s_prop=x, i_prop=y, plot=FALSE)
    
    mean_square_error_ <- sum((sim$Cases/city$pop-city$cases/city$pop)^2)
    
    return(mean_square_error_)
  }
  mean_square_error <- sapply(x, function(i) sapply(x, function(j) mse(s_prop[i], i_prop[j])))
  
  rownames(mean_square_error) <- sapply(1:length(i_prop), function(x) 
    paste("I_prop", x))
  
  colnames(mean_square_error) <- sapply(1:length(s_prop), function(x) 
    paste("S_prop", x))
  
  
  return(list(mse=mean_square_error, s_prop=s_prop, i_prop=i_prop))
}

validate_model <- function(city, betas, bayes, accuracy){
  initials <- choose_initials(city, betas, bayes)
  indices <- which(initials$mse == min(initials$mse), arr.ind=TRUE)
  
  i_prop <- initials$i_prop[indices[1]]
  s_prop <- initials$s_prop[indices[2]]
  
  sim_plot <- Sim(beta=rep_len(accuracy$beta_estimate, length.out=546), city=city, 
                  s_prop = s_prop, i_prop = i_prop, plot=TRUE)[[2]]
  
  return(list(initials=initials, indices=indices, chosen_props=c(i_prop=i_prop, s_prop=s_prop), sim_plot))
}

```



```{r Import Data, echo=FALSE}
#Read in Measles Data from Tycho Paper 
measles <- read.csv(file = "/Users/Kaitlyn/Documents/Thesis Work /Datasets/measlesUKUS.csv", header=TRUE, stringsAsFactors = FALSE)

measles_betas <- read.csv(file = "/Users/Kaitlyn/Documents/Thesis Work /Datasets/measeles biweekly betas.csv", header=TRUE, stringsAsFactors=FALSE)


```

```{r Susceptible Reconstruction, echo=FALSE}
#New York Reconstruction (12.52898 mins run time)
newyork <- read_in_city("NEW YORK", naremove=FALSE)[[1]]
ny_betas <- read_in_city("NEW YORK", naremove=FALSE)[[2]]

#scale_optim_ny <- optim_bandwidth(newyork)
scale_optim_ny <- 0.28 #from previous analysis 

newyork <- local_regression(newyork, scale_optim_ny)



#Chicago Reconstruction: removed 1 NA
chicago <- read_in_city("CHICAGO", naremove=TRUE)[[1]]
chicago_betas <- read_in_city("CHICAGO", naremove=TRUE)[[2]]
scale_optim_chicago <- 0.89 #WAY too high. Use NY scale optim

chicago <- local_regression(chicago, scale_optim_ny)


#Indianapolis
indianapolis <- read_in_city("INDIANAPOLIS", naremove=TRUE)[[1]]
indianapolis_betas <- read_in_city("INDIANAPOLIS", naremove=TRUE)[[2]]

indianapolis <- local_regression(indianapolis, scale_optim_ny)

#Spokane
spokane <- read_in_city("SPOKANE", naremove=FALSE)[[1]]
spokane_betas <- read_in_city("SPOKANE", naremove=FALSE)[[2]]

spokane <- fix_na(spokane, 1, 2, 2) #fix nas
spokane <- fix_na(spokane, 3, 2, 4)
spokane <- fix_na(spokane, 22, 21, 23)
spokane <- fix_na(spokane, m=c(43, 44), 42, 45)
spokane <- fix_na(spokane, m=47, 46, 48)
spokane <- fix_na(spokane, m=seq(49,53,1), 48, 54)
spokane <- fix_na(spokane, m=seq(56,60,1), 55, 61)
spokane <- fix_na(spokane, m=62, 61, 63)
spokane <- fix_na(spokane, m=seq(66,67,1), 65, 68)
spokane <- fix_na(spokane, m=seq(69,70,1), 68, 71)
spokane <- fix_na(spokane, m=72, 71, 73)
spokane <- fix_na(spokane, m=seq(79,80,1), 78, 81)
spokane <- fix_na(spokane, m=83, 82, 84)
spokane <- fix_na(spokane, m=85, 84, 86)
spokane <- fix_na(spokane, m=c(85, 86), 84, 87)
spokane <- fix_na(spokane, m=96, 95, 97)
spokane <- fix_na(spokane, m=112, 111, 113)

spokane <- local_regression(spokane, scale_optim_ny)

#New Orleans
neworleans <- read_in_city("NEW ORLEANS", naremove=TRUE)[[1]]
neworleans_betas <- read_in_city("NEW ORLEANS", naremove=TRUE)[[2]]

neworleans<-fix_na(neworleans, m=seq(38,43), 37, 44)
neworleans<-fix_na(neworleans, m=47, 46, 48)
neworleans<-fix_na(neworleans, m=seq(49,52), 48, 53)
neworleans<-fix_na(neworleans, m=seq(62,70), 61, 71)

neworleans <- local_regression(neworleans, scale_optim_ny)

# #Milwaukee
# milwaukee <- read_in_city("MILWAUKEE")[[1]]
# 
# #Minneapolis
# minneapolis <- read_in_city("MINNEAPOLIS")[[1]]
# 
# #Los Angeles
# LA <- read_in_city("LOS ANGELES", naremove=TRUE)[[1]]
# 
# #Washington
# washington <- read_in_city("WASHINGTON")[[1]]

```

```{r plots, eval=FALSE, include=FALSE}
#Boston Plots
SR_plot(boston, "Boston Susceptible Reconstruction")
IR_plot(boston, "Boston Infected Reconstruction")
rho_plot(boston, "Boston Rho")

#New York Plots
SR_plot(newyork, "New York Susceptible Reconstruction")
IR_plot(newyork, "New York Infected Reconstruction")
rho_plot(newyork, "New York Rho")

#Philadelphia Plots
SR_plot(phil, "Philadelphia Susceptible Reconstruction")
IR_plot(phil, "Philadelphia Infected Reconstruction")
rho_plot(phil, "Philadelphia Rho")


#Baltimore Plots
SR_plot(baltimore, "Baltimore Susceptible Reconstruction")
IR_plot(baltimore, "Baltimore Infected Reconstruction")
rho_plot(baltimore, "Baltimore Rho")

#St Louis Plots
SR_plot(stlouis, "St Louis Susceptible Reconstruction")
IR_plot(stlouis, "St Louis Infected Reconstruction")
rho_plot(stlouis, "St Louis Rho")

#Chicago Plots
SR_plot(chicago, "Chicago Susceptible Reconstruction")
IR_plot(chicago, "Chicago Infected Reconstruction")
rho_plot(chicago, "Chicago Rho")

#Detroit Plots
SR_plot(detroit, "Detroit Susceptible Reconstruction")
IR_plot(detroit, "Detroit Infected Reconstruction")
rho_plot(detroit, "Detroit Rho")

#Cleveland Plots
SR_plot(cleveland, "Cleveland Susceptible Reconstruction")
IR_plot(cleveland, "Cleveland Infected Reconstruction")
rho_plot(cleveland, "Cleveland Rho")

#Indianapolis Plots
SR_plot(indianapolis, "Indianapolis Susceptible Reconstruction")
IR_plot(indianapolis, "Indianapolis Infected Reconstruction")
rho_plot(indianapolis, "Indianapolis Rho")

#Spokane Plots
SR_plot(spokane, "Spokane Susceptible Reconstruction")
IR_plot(spokane, "Spokane Infected Reconstruction")
rho_plot(spokane, "Spokane Rho")

```


```{r Bayes Inference, eval=FALSE, include=FALSE}
ny_bayes <- run_bayes(newyork, which_stan = "high_pop")

chicago_bayes<- run_bayes(chicago, which_stan = "high_pop")

neworleans_bayes <- run_bayes(neworleans, which_stan = "high_pop") 

indianapolis_bayes <- run_bayes(indianapolis, which_stan = "high_pop") 

spokane_bayes <- run_bayes(spokane, which_stan = "high_pop") 
```

```{r Load Saved Bayes Outputs, include=FALSE}
load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/Chicago_Bayes")
load("/Users/Kaitlyn/Documents/Github/Thesis Git/NY_Bayes")
load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/Spokane_Bayes")
load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/Indianapolis_Bayes")
load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/NewOrleans_Bayes")

save(spokane_bayes, file="Spokane_Bayes")
save(indianapolis_bayes, file="Indianapolis_Bayes")
save(neworleans_bayes, file="NewOrleans_Bayes")
```

```{r Check Accuracy, include=FALSE}
#New York: Betas look very accurate! 
ny_accuracy <- accuracy_check(ny_betas, ny_bayes)

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=ny_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=ny_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="New York Beta Comparison")

#Chicago: Betas look very accurate using ny optim scale!
chicago_accuracy <- accuracy_check(chicago_betas, chicago_bayes)

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=chicago_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=chicago_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="Chicago Beta Comparison")

#Spokane:
spokane_accuracy <- accuracy_check(spokane_betas, spokane_bayes)

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=spokane_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=spokane_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="Spokane Beta Comparison")


#Indianapolis:
indianapolis_accuracy <- accuracy_check(indianapolis_betas, indianapolis_bayes)

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=indianapolis_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=indianapolis_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="Indianapolis Beta Comparison")


#New Orleans:
neworleans_accuracy <- accuracy_check(neworleans_betas, neworleans_bayes)

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=neworleans_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=neworleans_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="New Orleans Beta Comparison")


```

```{r Validating Model, echo=FALSE}
#New York
paste("New York Model")

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=ny_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=ny_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="New York Beta Comparison")

load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/ny_initials")

Sim(beta=rep_len(ny_accuracy$beta_estimate, length.out = 546), city=newyork, 
               s_prop=ny_initials[[3]][2], i_prop=ny_initials[[3]][1], 
               plot=TRUE)[[2]]

paste("New York Simulation MSE:", min(ny_initials[[1]]$mse)) 


#Chicago
paste("Chicago Model")

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=chicago_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=chicago_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="Chicago Beta Comparison")

load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/chicago_initials")

Sim(beta=rep_len(chicago_accuracy$beta_estimate, length.out = 546), city=chicago, 
               s_prop=chicago_initials[[3]][2], i_prop=chicago_initials[[3]][1], 
               plot=TRUE)[[2]]

paste("Chicago Simulation MSE:", min(chicago_initials[[1]]$mse))



#Indianapolis
paste("Indianapolis Model")

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=indianapolis_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=indianapolis_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="Indianapolis Beta Comparison")

load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/indianapolis_initials")

Sim(beta=rep_len(indianapolis_accuracy$beta_estimate, length.out = 546), 
    city=indianapolis, s_prop = indianapolis_initials[[3]][2], i_prop = 
    indianapolis_initials[[3]][1], plot=TRUE)[[2]]

paste("Indianapolis Simulation MSE:", min(indianapolis_initials[[1]]$mse))



#Spokane
paste("Spokane Model")

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=spokane_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=spokane_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="Spokane Beta Comparison")

load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/spokane_initials")

Sim(beta=rep_len(spokane_accuracy$beta_estimate, length.out=546), city=spokane, 
    s_prop = spokane_initials[[3]][2], i_prop = spokane_initials[[3]][1], 
    plot=TRUE)[[2]]

paste("Spokane Model MSE:", min(spokane_initials[[1]]$mse))



#New Orleans 
paste("New Orleans Model")

ggplot(, aes(x=seq(1,26,1)))+
  geom_point(aes(y=neworleans_accuracy$beta_estimate, col="Estimated Betas"))+
  geom_point(aes(y=neworleans_betas, col="Paper Betas"))+
  labs(x="biweek", y="beta", title="New Orleans Beta Comparison")

load("/Users/Kaitlyn/Documents/Github/Thesis Git/R Code/neworleans_initials")

Sim(beta=rep_len(neworleans_accuracy$beta_estimate, length.out=546), 
    city=neworleans, s_prop = neworleans_initials[[3]][2], i_prop = 
      neworleans_initials[[3]][1],  plot=TRUE)[[2]]

paste("New Orleans Model MSE:", min(neworleans_initials[[1]]$mse))



```


```{r Function Testing Center, eval=FALSE, include=FALSE}
```


```{r Checking out Data, eval=FALSE, include=FALSE}
#Test for lowest and highest populations
measles_<- measles %>%
  filter(year==1920, biweek==1)%>%
  select(loc, pop)
  
pop <- as.vector(measles_$pop)
names(pop) <- as.vector(measles_$loc)

sort(pop)
summary(pop)


#Lowest Pops (ascending order):  
#DULUTH       SPOKANE     READING.US SALT LAKE CITY      NASHVILLE        TRENTON 
#98917         104437         107784         118110         118342         119289

#Highest Pops (ascending order): 
#ST LOUIS    CLEVELAND      DETROIT PHILADELPHIA      CHICAGO     NEW YORK 
#772897       796841       993078      1823779      2701705      5620048 


#Find NA's in cities
measles_na <- measles %>%
  filter(year>1919 & year <1941)%>%
  group_by(loc) %>%
  mutate(number_na = sum(is.na(cases)==TRUE))

measles_na <- measles_na %>%
  filter(year==1920, biweek==1) %>%
  select(loc, number_na)

number_na <- as.vector(measles_na$number_na)
names(number_na) <- as.vector(measles_na$loc)
sort(number_na)
```

```{NA Notes, eval=FALSE, include=FALSE}
#NA Notes:

#Chicago: one NA at chicago$cases[71]. Sequence: 84 47 NA 54 56. Occurs at a trough. Decreasing prior to NA, increasing after.

#St Louis: 2 NAs at stlouis$cases[69,70]. Sequence: 17  8  3  5 NA NA  2  3  2  3. Occurs at a trough. Decreasing before NA, increasing after.

#Detroit: 1 NA at detroit$cases[88]. Sequence:  99 157 307 454  NA 715 649 336 112. Does not occur at trough - occurs at peak. Increasing and then decreasing. 

#Cleveland: 2 NAs at 34,35. Sequence:  46  62  84  70  NA  NA 107  98  90  63  33. Does not occur at true trough. 

#Indianapolis: 2 NAs at 18 and 39. Sequence: 125   28    7   12
#  4   NA    2    6   17   17    4    8   10   26   36   13   14   25   11   14
#   22   21    8   10    8   10   NA    4. Both occur at troughs - likely they are die outs. 

#LA: 4 NAs at 44, 69, 75, and 321. First 3 occur at definite troughs (2 cases reported on either side). The one at 321 also may be a trough/die out - it is between a 21 and a 32. 

#Spokane: 29 NAs at 1   3  22  43  44  47  49  50  51  52  53  56  57  58  59  60  62  66  67  69 70  72  79  80  83  85  86  96 112. All appear likely to be die outs, most occur where reported cases is less than 5 (exceptions: NA at spokane$cases[3] occurs between a 4 and 67. NA at spokane$cases[112] occurs between a 36 and 18).  ADDITIONAL NOTE: 0 is sometimes listed as a value of reported cases. 0 and NA are not synonymous (see spokane$cases[114])


#Spokane Fix NA:
spokane <- fix_na(spokane, 1, 2, 2)
spokane <- fix_na(spokane, 3, 2, 4)
spokane <- fix_na(spokane, 22, 21, 23)
spokane <- fix_na(spokane, m=c(43, 44), 42, 45)
spokane <- fix_na(spokane, m=47, 46, 48)
spokane <- fix_na(spokane, m=seq(49,53,1), 48, 54)
spokane <- fix_na(spokane, m=seq(56,60,1), 55, 61)
spokane <- fix_na(spokane, m=62, 61, 63)
spokane <- fix_na(spokane, m=seq(66,67,1), 65, 68)
spokane <- fix_na(spokane, m=seq(69,70,1), 68, 71)
spokane <- fix_na(spokane, m=72, 71, 73)
spokane <- fix_na(spokane, m=seq(79,80,1), 78, 81)
spokane <- fix_na(spokane, m=83, 82, 84)
spokane <- fix_na(spokane, m=85, 84, 86)
spokane <- fix_na(spokane, m=c(85, 86), 84, 87)
spokane <- fix_na(spokane, m=96, 95, 97)
spokane <- fix_na(spokane, m=112, 111, 113)

#St Louis Fix NA
stlouis <- fix_na(stlouis, m=c(69, 70), 68, 71)





```


```{r Subsampling Markov Chain, echo=FALSE}
chicago_betasample <- extract(chicago_bayes)$beta[seq(1,
                                                  nrow(extract(chicago_bayes)$beta),
                                                  1000),]


chicago_1000_sims <- apply(chicago_betasample, MARGIN=1, function(x) 
                           Sim(beta=rep_len(x, length.out = 546), city=chicago, 
                               s_prop=chicago_initials[[3]][2], i_prop = 
                               chicago_initials[[3]][1], plot=FALSE))


 g<- ggplot(chicago, aes(x=number))+
      geom_line(aes(y=cases), col="red")

  for(i in 1:600){
   g <- g + geom_line(data=chicago_1000_sims[[i+200]], aes(x=chicago$number, 
                                                           y=Cases), col="grey")
 }
 
print(g)

#need to 1) make vector of length 1000 for each time point (cases at time 1, cases at time 2, etc). 2) find 95% confidence interval at each point 


chicago_cases <- data.frame()
for(i in 1:1000){
  for(j in 1:546){
    chicago_cases[i,j] <- chicago_1000_sims[[i]]$Cases[j]
  }
}


confidence_interval <- function(x){
  a<-mean(x)
  s <- sd(x)
  n<-length(x)
  
  error <- qt(0.975,df=n-1)*s/sqrt(n)
  lower <- a-error
  upper <- a+error
  
  return(c(lower,upper))
}

credible_interval <- function(x){
  lower <- quantile(x, probs=.025, names=FALSE)
  upper <- quantile(x, probs=.975, names=FALSE)
  return(c(lower, upper))
}

test <- as.data.frame(t(apply(chicago_cases, MARGIN=2, confidence_interval))) #rows are upper/lower, columns are time points
test2 <- as.data.frame(t(apply(chicago_cases, MARGIN=2, credible_interval)))

names(test) <- c("lower", "upper")
names(test2) <- c("lower", "upper")

ggplot(test2, aes(x=chicago$number))+
  # geom_line(aes(y=lower, col="lower"))+
  # geom_line(aes(y=upper, col="upper"))+
  geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.6)+
  geom_line(aes(y=chicago$cases, col="data"))+
  geom_line(aes(y=test$Cases, col="sim"))


chicago_baseline <- Sim(beta=rep_len(chicago_accuracy$beta_estimate, length.out = 
                        546), city=chicago, s_prop=chicago_initials[[3]][2],
                        i_prop=chicago_initials[[3]][1], plot=FALSE)


test_function <- function(x){
  if(chicago_baseline$Cases[x] < test2[x,1]){
    dif <- test2[x,1] - chicago_baseline$Cases[x]
    return(dif)
  }
  if(chicago_baseline$Cases[x] > test2[x,2]){
    dif <-chicago_baseline$Cases[x] - test2[x,2]
    return(dif)
  }
  else{return(0)}
}

summary(sapply(seq(1, 546,1), test_function))
```


```{r}
min(ny_accuracy$beta_estimate)
min(ny_betas)

min(chicago_accuracy$beta_estimate)
min(chicago_betas)

min(indianapolis_accuracy$beta_estimate)
min(indianapolis_betas)

min(spokane_accuracy$beta_estimate)
min(spokane_betas)

min(neworleans_accuracy$beta_estimate)
min(neworleans_betas)
```



