---
title: "Tycho Measles Data 1935-1940 Philadelphia"
author: "Kaitlyn Stocker"
date: "11/30/2016"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)

##Format Data##
measles <- slice(MEASLES_Cases_1935.1940_20161130130229, 3:316)
measles <- select(measles, V1, V2, V3)
colnames(measles) <- c("Year", "Week", "Infecteds")
measles<- slice(measles, 2:314)

I <- as.numeric(measles$Infecteds)
I <- replace(I, 36, 5)
I <- replace(I, 172, 1023)
I <- replace(I, 250, 3)
N <- 1931334 #philadelphia population 
time <- seq(0,312)

##Infer number of R based on assumption that at time 0, there are 0 recovereds##
R<-0
for(n in 2:313){
  R[n]<-R[n-1]+I[n-1]
}

##Infer number of S based on number of I and R##
S<-0
for(n in 1:313){
  S[n]= N - (I[n] + R[n])
}

##Put S, I, and R into dataframe 
measlesdata <- list(time, S, I, R)
measlesdata <- as.data.frame(measlesdata)
colnames(measlesdata) <- c("time", "S", "I", "R")

ggplot(data=measlesdata, aes(x=time))+
  #geom_line(aes(y=S, col="S"))+
  geom_line(aes(y=I, col="I"))+
  geom_line(aes(y=R, col="R"))
```

###Inference using MLE
```{r}
#Define MLE Function 
MLE <- function(beta1, measlesdata){
likelihood <- function(beta1, results) {
  z <- 0
  for(j in 2:n){
    p <- (1-exp(-beta1*measlesdata$I[j-1]/N)) #probability of infection 
    z <- z - log(p^measlesdata$I[j] * (1-p)^measlesdata$S[j]) #negative log likelihood
  }
  return(z)
}
MLE <- optimise(likelihood, lower=0, upper=6, results=results)
return(MLE)
}

#Likelihood function for plotting 
likelihood <- function(beta1, results) {
  z <- 0
  out <- c(z)
  for(j in 2:n){
    p <- (1-exp(-beta1*results$I[j-1]/n)) #probability of infection 
    z <- z - log(p^results$I[j] * (1-p)^results$S[j]) #negative log likelihood
    out <- cbind(out, z)
  }
  out<-as.vector(out)
  return(out)
}

plot_likelihood <- function(likelihood){
  ggplot(MLE, aes(x=seq(1, 3, length.out=24)))+
    geom_line(aes(likelihood))
}

beta1 <- 1
estimate <- MLE(beta1=beta1, measlesdata)
estimate
likelihood1 <- likelihood(beta1=beta1, results)
plot_likelihood(likelihood1)
```

